# docs_environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f docs_environment.yml

name: tethys-docs

channels:
- tethysplatform
- conda-forge
- defaults

dependencies:
- python=3.6*
- tethys_dataset_services>=2.0.0
- django=2.1.*
- pip:
    - sphinx
    - mock
    - sphinx_rtd_theme
    - sphinxcontrib-napoleon
    - pbr
