# docs_environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f docs_environment.yml

name: tethys-docs

channels:
- tethysplatform
- conda-forge
- defaults

dependencies:
- python =3.7
- pip
- tethys_dataset_services >=2.0.0
- django =2.2.*
- sphinx =2.2.0
- sphinx-argparse
- pbr
- sphinxcontrib-napoleon
- pip:
    - sphinx_materialdesign_theme
