# docs_environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f docs_environment.yml

name: tethys-docs

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - tethys_dataset_services >=2.0.0
  - django =3.2.*
  - sphinx <7.2
  - sphinx-argparse
  - make
  - setuptools_scm
  - pip:
      - sphinxawesome-theme
      - sphinx-autobuild
      - sphinx_autodoc_typehints
